# /// script
# requires-python = ">=3.10"
# ///
"""LaTeX result tables for paper/main.tex, generated from the JSON result files (never typed by hand).

    python3 docs/tech-report/paper/make_tables.py           # writes paper/tables/*.tex
    python3 docs/tech-report/paper/make_tables.py --check   # also checks every number against report.md

Inputs (relative to the repository root):
  docs/tech-report/data/dev-rounds.json   DEV hill-climb rounds (Table: DEV rounds)
  docs/tech-report/data/hidden.json       HIDDEN one-shot gate, aggregate only (Table: HIDDEN)
  docs/TEST_RESULTS.json                  TEST comparison of six models (Tables: TEST a-d)
  docs/reference-dev.json                 DEV reference comparison (Table: DEV references)

--check parses the Markdown table with the same header in docs/tech-report/report.md and requires the numeric
tokens of every row to equal those of the generated row, so the PDF and the Markdown report cannot drift apart.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
OUT = HERE / "tables"
FAMILIES = ["apply_memory", "forgotten_violation", "needs_approval", "share_ok", "route", "notify_level", "pick_option"]
SAFETY = ["forgotten_violation", "needs_approval", "share_ok"]
API = {"Jev jev-1.13.0", "gpt-6-astra"}  # probabilities as returned (T = 1, no VAL fit): uncalibrated, no threshold
ADAPTER = "adapter r2-mix-s20260930"
TEX_NAME = {"B0 Qwen3.8-27B": r"B0 Qwen3.8-27B", "Jev jev-1.13.0": r"Jev \code{jev-1.13.0}", "Kev-27B": "Kev-27B",
            "Qwen3.5-4B": "Qwen3.5-4B", "gpt-6-astra": "gpt-6-astra", ADAPTER: r"\textbf{Adapter r2-mix}"}


def load(rel: str) -> dict:
    return json.loads((ROOT / rel).read_text(encoding="utf-8"))


# ---------------------------------------------------------------- number formatting (TeX and plain twins)
def num(x: float, d: int = 3) -> str:
    return f"{x:.{d}f}"


def tex_signed(s: str) -> str:
    return s.replace("-", "$-$")


def ci_plain(delta: float, lo: float, hi: float) -> str:
    return f"{100 * delta:+.1f} [{100 * lo:+.1f}, {100 * hi:+.1f}]"


def comma(n: int) -> str:
    return f"{n:,}"


def tex_cell(s: str) -> str:
    s = s.replace("−", "-")
    s = re.sub(r"(?<![\w$])-(?=\d)", "$-$", s)
    return s.replace(",", "{,}") if re.fullmatch(r"[\d,]+", s) else s


def bold(s: str) -> str:
    return rf"\textbf{{{s}}}"


class Table:
    """Collects rows as (tex cells, plain cells) so the TeX output and the --check comparison share one source."""

    def __init__(self, name: str, md_header: list[str]):
        self.name, self.md_header, self.rows = name, md_header, []

    def row(self, tex: list[str], plain: list[str]) -> None:
        self.rows.append((tex, plain))

    def write(self, preamble: str, header: str, postamble: str = "") -> None:
        self.write_body(preamble, header, "\n".join(" & ".join(t) + r" \\" for t, _ in self.rows), postamble)

    def write_body(self, preamble: str, header: str, body: str, postamble: str = "") -> None:
        OUT.mkdir(exist_ok=True)
        text = (f"% generated by make_tables.py from the JSON result files; do not edit\n"
                f"{preamble}\n\\toprule\n{header}\n\\midrule\n{body}\n\\bottomrule\n{postamble}\n")
        (OUT / f"{self.name}.tex").write_text(text, encoding="utf-8")
        print(f"tables/{self.name}.tex ({len(self.rows)} rows)")


# ---------------------------------------------------------------- tables
def dev_rounds(rounds: dict) -> Table:
    t = Table("dev_rounds", ["Training", "Change", "Rows / steps", "DEV macro"])
    base = rounds["baseline"]["base_dev"]
    t.row(["B0", "---", num(base["macro"]["accuracy"]), "---", "---",
           num(base["families"]["pick_option"]["accuracy"]), num(base["macro"]["brier"]),
           num(base["macro"]["coverage"], 2), "---"],
          ["B0", num(base["macro"]["accuracy"]), num(base["families"]["pick_option"]["accuracy"]),
           num(base["macro"]["brier"]), num(base["macro"]["coverage"], 2)])
    labels = {"r1-seedA": ("Round 1, seed A", "LoRA SFT on decision TRAIN"),
              "r1-seedB": ("Round 1, seed B", "same recipe, seed 20261003"),
              "r2-mix": ("Round 2, mix", "+ 30% Kev general rows"),
              "r2-7k": ("Round 2, 7k", "more decision data (2,729 records)")}
    for key, (label, change) in labels.items():
        r = rounds[key]
        rows_steps = f"{comma(r['recipe']['train_rows'])} / {r['recipe']['max_steps']}"
        acc = num(r["macro"]["cand"]["accuracy"])
        b = r["bootstrap"]
        ci = ci_plain(b["delta"], *b["ci95"])
        guard = f"{100 * r['guard']['delta']:+.2f}"
        pick = num(r["families"]["pick_option"]["cand"]["accuracy"])
        brier, cov = num(r["macro"]["cand"]["brier"]), num(r["macro"]["cand"]["coverage"], 2)
        dec = r["decision"].replace("_", " ")
        dec = {"rollback to base": "rollback (guard)", "advance to hidden": "advance to HIDDEN"}.get(dec, dec)
        win = r["decision"] == "advance_to_hidden"
        training = rf"{bold(label) if win else label}: {change.replace('%', chr(92) + '%')}"
        tex = [training, rows_steps, bold(acc) if win else acc, tex_signed(ci),
               bold(tex_signed(guard)) if win else tex_signed(guard), pick, brier, cov, bold(dec) if win else dec]
        t.row(tex, [label, change, rows_steps, acc, ci, guard, pick, brier, cov, dec])
    t.write(r"\begin{tabularx}{\linewidth}{@{}>{\raggedright\arraybackslash}X r c c c c c c "
            r">{\raggedright\arraybackslash}p{1.6cm}@{}}",
            r"Training: change & \shortstack{Rows /\\steps} & \shortstack{DEV\\macro} & "
            r"\shortstack{$\Delta$ vs B0 (pts)\\{[}95\% CI{]}} & \shortstack{Guard\\$\Delta$ (pts)} & "
            r"\shortstack{\fml{pick_}\\\fml{option}} & Brier & Cov. & Decision \\",
            r"\end{tabularx}")
    return t


def hidden(h: dict) -> Table:
    agg = h["aggregate"]
    t = Table("hidden", ["Family", "n scored", "B0 acc.", "Adapter acc."])
    for fam in FAMILIES:
        f = agg["families"][fam]
        b, c = f["base"], f["cand"]
        ci = ci_plain(f["accuracy_delta"], *f["accuracy_delta_ci95"])
        plain = [fam, comma(c["n_scored"]), num(b["accuracy"]), num(c["accuracy"]), ci,
                 num(b["brier"]), num(c["brier"]), num(b["ece"]), num(c["ece"]),
                 num(b["coverage"], 2), num(c["coverage"], 2), num(b["realized_error"]), num(c["realized_error"])]
        tex = [rf"\fml{{{fam}}}"] + [tex_cell(x) for x in plain[1:4]] + [tex_signed(ci)] + plain[5:]
        if fam == "pick_option":
            tex[-1] = bold(tex[-1])
        t.row(tex, plain)
    m, ms = agg["macro"], agg["bootstrap"]
    ci = ci_plain(ms["delta"], *ms["ci95"])
    n = agg["macro"]["micro"]["cand"]["n_scored"]
    plain = ["Macro", comma(n), num(m["base"]["accuracy"]), num(m["cand"]["accuracy"]), ci,
             num(m["base"]["brier"]), num(m["cand"]["brier"]), num(m["base"]["ece"]), num(m["cand"]["ece"]),
             num(m["base"]["coverage"], 2), num(m["cand"]["coverage"], 2), num(m["base"]["realized_error"]),
             num(m["cand"]["realized_error"])]
    tex = [r"\textbf{Macro}", tex_cell(plain[1]), bold(plain[2]), bold(plain[3]), bold(tex_signed(ci))] + plain[5:]
    t.rows.append(([r"\midrule " + tex[0]] + tex[1:], plain))
    t.write(r"\begin{tabular}{@{}lrccc cc cc cc cc@{}}",
            r" & & \multicolumn{3}{c}{Accuracy} & \multicolumn{2}{c}{Brier} & \multicolumn{2}{c}{ECE} & "
            r"\multicolumn{2}{c}{Coverage} & \multicolumn{2}{c}{Real.\ error} \\" "\n"
            r"\cmidrule(lr){3-5}\cmidrule(lr){6-7}\cmidrule(lr){8-9}\cmidrule(lr){10-11}\cmidrule(l){12-13}" "\n"
            r"Family & $n$ & B0 & Adapter & \shortstack{$\Delta$ (pts)\\{[}95\% CI{]}} & B0 & Ad. & B0 & Ad. & B0 & Ad. & B0 & Ad. \\",
            r"\end{tabular}")
    return t


def order(preds: dict, key=lambda b: b["macro_accuracy"]) -> list[str]:
    return sorted(preds, key=lambda p: key(preds[p]))


def fam_header() -> str:
    cells = []
    for f in FAMILIES:
        a, _, b = f.partition("_")
        mark = r"$^\dagger$" if f == "pick_option" else ""
        top, bottom = (a, b) if b else (r"\strut", a)
        cells.append(rf"\shortstack{{{top}\\{bottom}{mark}}}")
    return " & ".join(cells)


def test_family(test: dict) -> Table:
    preds = test["predictors"]
    t = Table("test_family", ["Model", "Macro", "apply_memory", "forgotten_violation"])
    for p in order(preds, key=lambda b: b["all"]["macro_accuracy"]):
        b = preds[p]["all"]
        star = r"$^*$" if p in API else ""
        fams = [num(b["families"][f]["accuracy"]) for f in FAMILIES]
        cov = "n/a" if b.get("automation_coverage") is None else num(b["automation_coverage"], 2)
        plain = [p, num(b["macro_accuracy"])] + fams + [num(b["macro_brier"]), num(b["macro_ece"]), cov]
        macro = bold(plain[1]) if p == ADAPTER else plain[1]
        tex = [TEX_NAME[p], macro] + fams + [plain[-3] + star, plain[-2] + star, cov]
        t.row(tex, plain)
    t.write(r"\begin{tabular}{@{}lc ccccccc ccc@{}}",
            rf"Model & Macro & {fam_header()} & Brier & ECE & \shortstack{{Cov.\\@5\%}} \\", r"\end{tabular}")
    return t


def test_halves(test: dict) -> Table:
    preds, sens = test["predictors"], test["sensitivity_excl_pick_option"]["predictors"]
    t = Table("test_halves", ["Model", "All", "A half (gpt-6-astra)", "B half (Claude Opus 5.5)"])
    for p in order(preds, key=lambda b: b["all"]["macro_accuracy"]):
        vals = [num(preds[p][h]["macro_accuracy"]) for h in ("all", "A", "B")]
        gap = f"{100 * (preds[p]['B']['macro_accuracy'] - preds[p]['A']['macro_accuracy']):+.1f}"
        six = [num(sens[p][h]["macro_accuracy"]) for h in ("all", "A", "B")]
        plain = [p] + vals + [gap] + six
        win = p == ADAPTER
        tex = [TEX_NAME[p]] + [bold(v) if win else v for v in vals] + [tex_signed(gap)] + \
              [bold(v) if win else v for v in six]
        t.row(tex, plain)
    t.write(r"\begin{tabular}{@{}l ccc c ccc@{}}",
            r" & \multicolumn{3}{c}{Primary: 7 families} & & \multicolumn{3}{c}{Sensitivity: 6 families} \\" "\n"
            r"\cmidrule(lr){2-4}\cmidrule(l){6-8}" "\n"
            r"Model & All & A half & B half & B $-$ A (pts) & All & A & B \\"
            "\n" r" & & (gpt-6-astra) & (Claude Opus 5.5) & & & & \\",
            r"\end{tabular}")
    return t


def test_paired(test: dict) -> Table:
    pairs, spairs = test["paired_adapter_vs"], test["sensitivity_excl_pick_option"]["paired_adapter_vs"]
    t = Table("test_paired", ["Adapter − model", "All", "A half", "B half"])
    keys = sorted(pairs, key=lambda k: pairs[k]["all"]["delta"])
    groups = {"primary": [], "sensitivity": []}
    for k in keys:
        name = k.removeprefix("adapter - ")
        prim = [ci_plain(pairs[k][h]["delta"], *pairs[k][h]["ci95"]) for h in ("all", "A", "B")]
        sec = [ci_plain(spairs[k][h]["delta"], *spairs[k][h]["ci95"]) for h in ("all", "A", "B")]
        t.row([], [name] + prim + sec)  # plain row in report.md column order, for --check
        groups["primary"].append(" & ".join([TEX_NAME[name]] + [tex_signed(x) for x in prim]) + r" \\")
        groups["sensitivity"].append(" & ".join([TEX_NAME[name]] + [tex_signed(x) for x in sec]) + r" \\")
    holm = sorted({v["p_holm"] for d in (pairs, spairs) for k in d for v in d[k].values()})
    one = max(v["p_one_sided"] for d in (pairs, spairs) for k in d for v in d[k].values())
    t.meta = {"holm": holm, "p_one_sided_max": one}
    body = (r"\multicolumn{4}{@{}l}{\emph{Primary: 7 families}} \\" "\n" + "\n".join(groups["primary"]) + "\n"
            r"\midrule" "\n" r"\multicolumn{4}{@{}l}{\emph{Amendment-7 sensitivity: 6 families, without "
            r"\fml{pick_option}}} \\" "\n" + "\n".join(groups["sensitivity"]))
    t.write_body(r"\begin{tabular}{@{}l ccc@{}}", r"Adapter $-$ model & All & A half & B half \\", body,
                 r"\end{tabular}")
    return t


def test_safety(test: dict) -> Table:
    preds = test["predictors"]
    t = Table("test_safety", ["Model", "forgotten_violation", "needs_approval", "share_ok"])
    for p in order(preds, key=lambda b: b["all"]["macro_accuracy"]):
        r = preds[p]["all"]["safety_fn_rate"]
        plain = [p] + [f"{100 * r[f]:.1f}%" for f in SAFETY]
        t.row([TEX_NAME[p]] + [x.replace("%", r"\%") for x in plain[1:]], plain)
    t.write(r"\begin{tabular}{@{}lccc@{}}",
            r"Model & " + " & ".join(rf"\fml{{{f}}}" for f in SAFETY) + r" \\", r"\end{tabular}")
    return t


def dev_references(ref: dict) -> Table:
    preds = ref["predictors"]
    t = Table("dev_references", ["Predictor", "Macro", "apply_memory", "forgotten_violation"])
    for p in order(preds):
        b = preds[p]
        star = r"$^*$" if p in API else ""
        fams = [num(b["families"][f]["accuracy"]) for f in FAMILIES]
        plain = [p, num(b["macro_accuracy"])] + fams + [num(b["macro_brier"]), num(b["macro_ece"])]
        macro = bold(plain[1]) if p == ADAPTER else plain[1]
        t.row([TEX_NAME[p], macro] + fams + [plain[-2] + star, plain[-1] + star], plain)
    hdr = fam_header().replace(r"$^\dagger$", "")
    t.write(r"\begin{tabular}{@{}lc ccccccc cc@{}}", rf"Predictor & Macro & {hdr} & Brier & ECE \\",
            r"\end{tabular}")
    return t


# ---------------------------------------------------------------- check against report.md
NUM = re.compile(r"[+\-−]?\d[\d,]*(?:\.\d+)?")


def numbers(cells: list[str]) -> list[str]:
    out = []
    for c in cells:
        c = re.sub(r"`[^`]*`", "", c)  # identifiers such as `jev-1.13.0`
        for m in NUM.findall(c.replace("−", "-")):
            out.append(m.replace(",", "") if re.fullmatch(r"[+\-]?\d[\d,]*", m) else m)
    return out


def md_tables(md: str) -> list[list[list[str]]]:
    tables, cur = [], []
    for line in md.splitlines():
        if line.startswith("|"):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if not all(re.fullmatch(r":?-+:?", c) for c in cells):
                cur.append(cells)
        elif cur:
            tables.append(cur)
            cur = []
    if cur:
        tables.append(cur)
    return tables


def norm(s: str) -> str:
    return re.sub(r"[*`]", "", s).strip()


def check(tables: list[Table]) -> int:
    md = md_tables((ROOT / "docs/tech-report/report.md").read_text(encoding="utf-8"))
    bad = 0
    for t in tables:
        hits = [m for m in md if [norm(c) for c in m[0][:len(t.md_header)]] == t.md_header]
        if len(hits) != 1:
            print(f"CHECK {t.name}: expected 1 Markdown table with header {t.md_header}, found {len(hits)}")
            bad += 1
            continue
        rows = hits[0][1:]
        if len(rows) != len(t.rows):
            print(f"CHECK {t.name}: {len(rows)} Markdown rows vs {len(t.rows)} generated")
            bad += 1
            continue
        for (_, plain), mrow in zip(t.rows, rows):
            # the row label may itself contain digits (model names); compare the numeric cells only
            g, m = numbers(plain[1:]), numbers(mrow[1:])
            if g != m:
                print(f"CHECK {t.name} row {norm(mrow[0])!r}: generated {g} != report.md {m}")
                bad += 1
        print(f"CHECK {t.name}: {len(rows)} rows " + ("OK" if not bad else "see above"))
    return bad


def main() -> None:
    rounds, hid = load("docs/tech-report/data/dev-rounds.json"), load("docs/tech-report/data/hidden.json")
    test, ref = load("docs/TEST_RESULTS.json"), load("docs/reference-dev.json")
    tables = [dev_rounds(rounds), hidden(hid), test_family(test), test_halves(test), test_paired(test),
              test_safety(test), dev_references(ref)]
    paired = tables[4]
    print(f"TEST paired: Holm-adjusted p values {paired.meta['holm']}, max one-sided p {paired.meta['p_one_sided_max']:.2g}")
    if "--check" in sys.argv[1:]:
        bad = check(tables)
        if bad:
            raise SystemExit(f"{bad} mismatch(es) between generated tables and report.md")
        print("all generated tables match report.md")


if __name__ == "__main__":
    main()
